spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/User_ServiceDb
        driver-class-name: org.postgresql.Driver
        username: hemanth
        password: hemanth
        hikari:
          connection-init-sql: SET TIME ZONE 'Asia/Kolkata';  # This ensures every connection uses correct timezone

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata   # IMPORTANT: Hibernate will use this timezone

server:
  port: 8081
